const plantData = {
  wildflowers: [
    {
      englishName: "Northeastern beardtongue",
      latinName: "Penstemon hirsutus",
      fileExt: "northeastern-beardtongue",
      family: "Beardtongues",
      price: "4.75",
      description: `Low, dark green foliage with numerous white-to-pale-lavender flowers blooms in early summer attracting pollinating insects and hummingbirds. Must have well drained soil. A short-lived perennial but will reseed if happy. Excellent for stone walls and rock gardens.`,
      native: "Yes",
      growingConditions: `Sun to part shade in dry to medium soil`,
      height: `16\"`,
      blooms: "In early summer",
      naturalHabitat:
        "Dry, rocky woodland edges and meadows, ledges, and disturbed areas",
      seedsPerPacket: "50-100",
      germination: ["B"],
      germNotes:
        "These seeds need a winter or cold period to germinate - a minimum of 60 days below 40°F in moist soil (or sand or vermiculite). Sow outdoors in pots November through February. A great species for beginner seed-sowers.",
      pairs: "",
      id: 1,
    },
    {
      englishName: "Blood-root",
      latinName: "Sanguinaria canadensis",
      fileExt: "blood-root",
      family: "",
      price: "4.75",
      description: `One of the first wildflowers to emerge in early spring with delicate, white 1-2 inch flowers with yellow centers that are visited by the first pollinating insects. After bloom, the distinctive large, deeply-lobed foliage adds a distinctive texture to the woodland garden.`,
      native: "Yes",
      growingConditions: `Full shade in medium soil`,
      height: `12\"`,
      blooms: "In early spring",
      naturalHabitat: "Rich deciduous woods",
      seedsPerPacket: "45-50 (moist-stratified)",
      germination: ["E", "F"],
      germNotes:
        "Sow these seeds immediately upon receipt, outdoors in pots from November through February. This seed has a double dormancy so look for germination the second spring. This species is challenging to grow, and a great species for more experienced seed-sowers.",
      pairs: "Blue lobelia and red baneberry",
      id: 2,
    },
    {
      englishName: "Eastern shooting star",
      latinName: "Dodecatheon meadia",
      fileExt: "eastern-shooting-star",
      family: "",
      price: "4.75",
      description:
        "An early-blooming spring ephemeral with deep pink star-shaped flowers held above a rosette of low green foliage. Flowers attract early pollinators. Deer-resistant. Plants go dormant in late summer.",
      native: "No. Native south and west of New England.",
      growingConditions: `Sun to part shade in medium soil`,
      height: `12\"`,
      blooms: "In early spring",
      naturalHabitat: "Open woodlands and meadows with moist soil",
      seedsPerPacket: "45-50 (moist-stratified)",
      germination: ["B"],
      germNotes: `These seeds require a cold period to germinate - a minimum of 21 days below 40°F in moist soil (or sand or vermiculite). Sow outdoors in pots, on the soil surface and leave uncovered, November through February. This species is challenging to grow, and a great species for more experienced seed-sowers.
        *These seeds have been known to germinate without a cold period, best practice is to allow a minimum of 21 days of cold.`,
      pairs: "Jacob's-ladder and spotted crane's-bill",
      id: 3,
    },
    {
      englishName: "New England aster",
      latinName: "Symphyotrichum novae-angliae",
      fileExt: "new-england-aster",
      family: "Asters",
      price: "4.75",
      description: `A fall-blooming meadow aster with bright purple or pink flowers and yellow centers. Dark green foliage can be cut back in mid-summer to control height. Flowers supply abundant nectar for late-season bees and butterflies. Foliage important for many species in their larval stages. Excellent garden and landscape plant with late season interest.`,
      native: "Yes",
      growingConditions: `Sun to part shade in medium to wet soil`,
      height: `2-5\'`,
      blooms: "In late fall",
      naturalHabitat:
        "Meadows, roadsides, and ditches with fertile, moist soils",
      seedsPerPacket: "50-100",
      germination: ["A"],
      germNotes:
        "These seeds do not need a winter or cold period to germinate - the rate of germination may be higher if the seeds are exposed to a period of cold, but it is not required. Sow outdoors in pots November through early April. A great species for beginner seed-sowers.",
      pairs: "",
      id: 0,
    },
    {
      englishName: "Cardinal flower",
      latinName: "Lobelia cardinalis",
      fileExt: "cardinal-flower",
      family: "",
      price: "4.75",
      description:
        "In midsummer, tall spikes of deep red flowers cover the plant and attract hummingbirds and butterflies. A dramatic plant for moist gardens and wet areas in sun or shade. A short-lived perennial that will reseed readily if happy.",
      native: "Yes.",
      growingConditions: `Sun to shade in moist to wet soil`,
      height: `2-3\'`,
      blooms: "In midsummer",
      naturalHabitat: "Wetlands and streamsides",
      seedsPerPacket: "50-100",
      germination: ["B", "C"],
      germNotes: `These seeds require a cold period to germinate - a minimum of 60 days below 40°F in moist soil (or sand or vermiculite). Sow outdoors in pots, on the soil surface and leave uncovered, November through February. A great species for beginner seed-sowers.`,
      pairs: "Boneset and blue iris in sunny areas; ferns in shady areas",
      id: 4,
    },
    {
      englishName: "Black-eyed coneflower",
      latinName: "Rudbeckia hirta",
      fileExt: "black-eyed-coneflower",
      family: "",
      price: "4.75",
      description:
        "A bright golden-yellow meadow coneflower with a black center that blooms from mid-summer to fall. It attracts numerous butterflies when in bloom, and birds to its seed heads. Thrives in poor, dry soils. Will bloom the first year from seed; easy to establish in waste areas. A good urban plant for sunny dry locations.",
      native:
        "No. Grows wild in Maine but is naturalized from west of New England.",
      growingConditions: `Sun in dry soil`,
      height: `2'`,
      blooms: "In mid-summer",
      naturalHabitat: "Dry meadows, roadsides, and disturbed areas",
      seedsPerPacket: "50-100",
      germination: ["A"],
      germNotes: `These seeds do not need a winter or cold period to germinate. Sow outdoors in pots November through April. A great species for beginner seed-sowers.`,
      pairs: "Butterfly milkweed and smooth blue aster",
      id: 5,
    },
    {
      lenapeName: "wisaòtaèk",
      lenapeTalkingDict: "https://www.talk-lenape.org/detail?id=11278",
      lenapeNameMeaning: "yellow flower",
      englishName: "Canadian goldenrod",
      latinName: "Solidago canadensis",
      fileExt: " canadian-goldenrod",
      family: "Asteraceae",
      price: "4.75",
      description:
        "Provides vital sources of pollen and nectar for bees and other insects in the late summer and fall throughout North America. Canada goldenrod can be used for revegetation of disturbed areas, for mine spoil reclamation, and soil stabilization.",
      native: "Yes.",
      growingConditions: "Full sun",
      height: `4-5'`,
      blooms: "In late fall",
      naturalHabitat: "",
      seedsPerPacket: "50-100",
      germination: ["B"],
      germNotes:
        "These seeds need a winter or cold period to germinate - a minimum of 60 days below 40°F in moist soil (or sand or vermiculite). Sow outdoors in pots November through February. A great species for beginner seed-sowers.",
      id: 6,
    },
    {
      lenapeName: "",
      lenapeTalkingDict: "",
      englishName: "",
      latinName: "Solidago caesia",
      fileExt: " blue-stem-goldenrod",
      family: "Asteraceae",
      price: "4.75",
      description:
        "A lovely goldenrod for shady gardens and landscapes. In October, delicate arching stems are covered with tiny yellow flower clusters that attract fall pollinators. A clump-forming species that is very well-behaved and deserving of a place in shady gardens. Deer-proof.",
      native: "Yes.",
      growingConditions: "Part sun to shade in dry to medium soil",
      height: `18"`,
      blooms: "In late fall",
      naturalHabitat: "Dry deciduous woodlands and shady edges",
      seedsPerPacket: "50-100",
      germination: ["B"],
      germNotes:
        "These seeds need a winter or cold period to germinate - a minimum of 60 days below 40°F in moist soil (or sand or vermiculite). Sow outdoors in pots November through February. A great species for beginner seed-sowers.",
      id: 7,
    },
  ],
};

export default plantData;
